CREATE TABLE IF NOT EXISTS teams
(
    id SERIAL PRIMARY KEY,
    team_name TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS users
(
    id SERIAL PRIMARY KEY,
    username TEXT NOT NULL,
    team_id INTEGER REFERENCES teams (id),
    is_active BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS users_id
(
    id INTEGER REFERENCES users (id),
    user_id TEXT NOT NULL UNIQUE
);
